/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inverse.matrix;

import java.beans.PropertyVetoException;
import static java.lang.Math.abs;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.KeyEvent;
import javax.swing.plaf.InternalFrameUI;

/**
 *
 * @author genwockz
 */
public class Input extends javax.swing.JFrame {
float answer,determinant,ABSdet;
float aa1,aa2,aa3,aa4,aa5,aa6,aa7,aa8,aa9;
float bb1,bb2,bb3,bb4,bb5,bb6,bb7,bb8,bb9;
    /**
     * Creates new form Input
     */
    public Input() {
     
             initComponents();
             
     
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        a4 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        a8 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        a9 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jAnswer = new javax.swing.JLabel();
        choose = new javax.swing.JButton();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        b5 = new javax.swing.JTextField();
        b6 = new javax.swing.JTextField();
        b7 = new javax.swing.JTextField();
        b8 = new javax.swing.JTextField();
        b9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setBounds(new java.awt.Rectangle(392, 149, 628, 358));
        setMaximumSize(new java.awt.Dimension(628, 358));
        setMinimumSize(new java.awt.Dimension(628, 358));
        setPreferredSize(new java.awt.Dimension(628, 358));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("by:GenCarcedo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 90, -1));

        a4.setBackground(new java.awt.Color(240, 240, 240));
        a4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a4.setBorder(null);
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        a4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a4KeyTyped(evt);
            }
        });
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 70, 60));

        a2.setBackground(new java.awt.Color(240, 240, 240));
        a2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a2.setBorder(null);
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a2KeyTyped(evt);
            }
        });
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 30, 70, 60));

        a5.setBackground(new java.awt.Color(240, 240, 240));
        a5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a5.setBorder(null);
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        a5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a5KeyTyped(evt);
            }
        });
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 110, 70, 60));

        a8.setBackground(new java.awt.Color(240, 240, 240));
        a8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a8.setBorder(null);
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });
        a8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a8KeyTyped(evt);
            }
        });
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 200, 70, 60));

        a7.setBackground(new java.awt.Color(240, 240, 240));
        a7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a7.setBorder(null);
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });
        a7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a7KeyTyped(evt);
            }
        });
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, 60));

        a9.setBackground(new java.awt.Color(240, 240, 240));
        a9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a9.setBorder(null);
        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });
        a9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a9KeyTyped(evt);
            }
        });
        getContentPane().add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 70, 60));

        a6.setBackground(new java.awt.Color(240, 240, 240));
        a6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a6.setBorder(null);
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        a6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a6KeyTyped(evt);
            }
        });
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 70, 60));

        a1.setBackground(new java.awt.Color(240, 240, 240));
        a1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a1.setBorder(null);
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a1KeyTyped(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 60));

        a3.setBackground(new java.awt.Color(240, 240, 240));
        a3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a3.setBorder(null);
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        a3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a3KeyTyped(evt);
            }
        });
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 30, 70, 60));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, -1));

        jButton1.setText("S O L V E");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 90, -1));

        jButton3.setText("Solve Again");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Matrix.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setText("Determinant:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, 20));
        getContentPane().add(jAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 290, 50, 20));

        choose.setText("Inverse");
        choose.setEnabled(false);
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        getContentPane().add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 90, -1));

        b1.setBackground(new java.awt.Color(240, 240, 240));
        b1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1.setBorder(null);
        b1.setEnabled(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b1KeyTyped(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 70, 60));

        b2.setBackground(new java.awt.Color(240, 240, 240));
        b2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2.setBorder(null);
        b2.setEnabled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        b2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b2KeyTyped(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 70, 60));

        b3.setBackground(new java.awt.Color(240, 240, 240));
        b3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3.setBorder(null);
        b3.setEnabled(false);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        b3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b3KeyTyped(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 70, 60));

        b4.setBackground(new java.awt.Color(240, 240, 240));
        b4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b4.setBorder(null);
        b4.setEnabled(false);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        b4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b4KeyTyped(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 70, 60));

        b5.setBackground(new java.awt.Color(240, 240, 240));
        b5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b5.setBorder(null);
        b5.setEnabled(false);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        b5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b5KeyTyped(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 70, 60));

        b6.setBackground(new java.awt.Color(240, 240, 240));
        b6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b6.setBorder(null);
        b6.setEnabled(false);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        b6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b6KeyTyped(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 70, 60));

        b7.setBackground(new java.awt.Color(240, 240, 240));
        b7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b7.setBorder(null);
        b7.setEnabled(false);
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        b7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b7KeyTyped(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 70, 60));

        b8.setBackground(new java.awt.Color(240, 240, 240));
        b8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b8.setBorder(null);
        b8.setEnabled(false);
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        b8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b8KeyTyped(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 70, 60));

        b9.setBackground(new java.awt.Color(240, 240, 240));
        b9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b9.setBorder(null);
        b9.setEnabled(false);
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        b9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b9KeyTyped(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 70, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Matrix.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(a1.getText().equals("") || a2.getText().equals("") || a3.getText().equals("") || a4.getText().equals("") || a5.getText().equals("") || a6.getText().equals("") || a7.getText().equals("") || a8.getText().equals("") || a9.getText().equals("") ){ 
        getToolkit().beep();
        }else{
        
        
        aa1=  Float.parseFloat(a1.getText());
        aa2=  Float.parseFloat(a2.getText());
        aa3=  Float.parseFloat(a3.getText());
        aa4=  Float.parseFloat(a4.getText());
        aa5=  Float.parseFloat(a5.getText());
        aa6=  Float.parseFloat(a6.getText());
        aa7=  Float.parseFloat(a7.getText());
        aa8=  Float.parseFloat(a8.getText());
        aa9=  Float.parseFloat(a9.getText());
        
     determinant = ((aa1*aa5*aa9)+(aa2*aa6*aa7)+(aa3*aa4*aa8))-((aa7*aa5*aa3)+(aa8*aa6*aa1)+(aa9*aa4*aa2));
     
    
     
     
        
     
     
     
     
     
     
     
     
            this.jAnswer.setText(String.valueOf(determinant));
            jAnswer.setToolTipText(String.valueOf(determinant));
            NoAndar();
       answersaMATRIX();
       
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
public void answersaMATRIX(){
 
    if(choose.getText().equals("Inverse")){
        if(determinant==0){
        
    b1.setText("0");
    b2.setText("0");
    b3.setText("0");
    b4.setText("0");
    b5.setText("0");
    b6.setText("0");
    b7.setText("0");
    b8.setText("0");
    b9.setText("0");
        }else{
    float z=(1/Math.abs(determinant));
        System.out.println(z);
        
    bb1 = (z*((aa8*aa6)-(aa5*aa9)));
    bb2 = (z*((aa8*aa3)-(aa2*aa9)))*(-1);
    bb3= z*((aa5*aa3)-(aa2*aa6));
    bb4 = (z*((aa7*aa6)-(aa4*aa9)))*(-1);
    bb5 = z*((aa7*aa3)-(aa1*aa9));
    bb6 = (z*((aa4*aa3)-(aa1*aa6)))*(-1);
    bb7 = z*((aa7*aa5)-(aa4*aa8));
    bb8 = (z*((aa7*aa2)-(aa1*aa8)))*(-1);
    bb9 =  z*((aa4*aa2)-(aa1*aa5));  
    
        DecimalFormat df = new DecimalFormat();
    df.setMaximumFractionDigits(4); 
    b1.setText(String.valueOf(df.format(bb1)));
    b1.setToolTipText(String.valueOf(df.format(bb1)));
    b2.setText(String.valueOf(df.format(bb2)));
    b2.setToolTipText(String.valueOf(df.format(bb2)));
    b3.setText(String.valueOf(df.format(bb3)));
    b3.setToolTipText(String.valueOf(df.format(bb3)));
    b4.setText(String.valueOf(df.format(bb4)));
    b4.setToolTipText(String.valueOf(df.format(bb4)));
    b5.setText(String.valueOf(df.format(bb5)));
    b5.setToolTipText(String.valueOf(df.format(bb5)));
    b6.setText(String.valueOf(df.format(bb6)));
    b6.setToolTipText(String.valueOf(df.format(bb6)));
    b7.setText(String.valueOf(df.format(bb7)));
    b7.setToolTipText(String.valueOf(df.format(bb7)));
    b8.setText(String.valueOf(df.format(bb8)));
    b8.setToolTipText(String.valueOf(df.format(bb8)));
    b9.setText(String.valueOf(df.format(bb9)));
    b9.setToolTipText(String.valueOf(df.format(bb9)));
        
        }
    }else if(choose.getText().equals("Cofactor")){
    
    bb1 = (aa8*aa6)-(aa5*aa9);
    bb2 = ((aa7*aa6)-(aa4*aa9))*(-1);
    bb3= ((aa7*aa5)-(aa4*aa8));
    bb4 = ((aa8*aa3)-(aa2*aa9))*(-1);
    bb5 = ((aa7*aa3)-(aa1*aa9));
    bb6 = ((aa7*aa2)-(aa1*aa8))*(-1);
    bb7 = ((aa5*aa3)-(aa2*aa6));
    bb8 = ((aa4*aa3)-(aa1*aa6))*(-1);
    bb9 =  ((aa4*aa2)-(aa1*aa5));  
        
        
      

        
     DecimalFormat df = new DecimalFormat();
    df.setMaximumFractionDigits(2);
    b1.setText(String.valueOf(df.format(bb1)));
    b1.setToolTipText(String.valueOf(df.format(bb1)));
    b2.setText(String.valueOf(df.format(bb2)));
    b2.setToolTipText(String.valueOf(df.format(bb2)));
    b3.setText(String.valueOf(df.format(bb3)));
    b3.setToolTipText(String.valueOf(df.format(bb3)));
    b4.setText(String.valueOf(df.format(bb4)));
    b4.setToolTipText(String.valueOf(df.format(bb4)));
    b5.setText(String.valueOf(df.format(bb5)));
    b5.setToolTipText(String.valueOf(df.format(bb5)));
    b6.setText(String.valueOf(df.format(bb6)));
    b6.setToolTipText(String.valueOf(df.format(bb6)));
    b7.setText(String.valueOf(df.format(bb7)));
    b7.setToolTipText(String.valueOf(df.format(bb7)));
    b8.setText(String.valueOf(df.format(bb8)));
    b8.setToolTipText(String.valueOf(df.format(bb8)));
    b9.setText(String.valueOf(df.format(bb9)));
    b9.setToolTipText(String.valueOf(df.format(bb9)));
    }

}
    
    public void Andar(){
    
    
        choose.setEnabled(false);
        jAnswer.setText("");
    a1.setEnabled(true);
    a2.setEnabled(true);
    a3.setEnabled(true);
    a4.setEnabled(true);
    a5.setEnabled(true);
    a6.setEnabled(true);
    a7.setEnabled(true);
    a8.setEnabled(true);
    a9.setEnabled(true);
    jButton1.setEnabled(true);
    jButton2.setEnabled(true);
    
    }
    
    public void NoAndar(){
    jButton3.setEnabled(true);
    choose.setEnabled(true);
    a1.setEnabled(false);
    a2.setEnabled(false);
    a3.setEnabled(false);
    a4.setEnabled(false);
    a5.setEnabled(false);
    a6.setEnabled(false);
    a7.setEnabled(false);
    a8.setEnabled(false);
    a9.setEnabled(false);
    jButton1.setEnabled(false);
    jButton2.setEnabled(false);
    
    }
    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a4ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a5ActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a8ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a7ActionPerformed

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a9ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a6ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a3ActionPerformed

    private void a1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==evt.VK_MINUS || c==evt.VK_PERIOD ) ){
        getToolkit().beep();
        evt.consume();
        }
        
        
    }//GEN-LAST:event_a1KeyTyped

    private void a2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a2KeyTyped
        // TODO add your handling code here:
       // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==evt.VK_MINUS || c==evt.VK_PERIOD ) ){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_a2KeyTyped

    private void a3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a3KeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==evt.VK_MINUS || c==evt.VK_PERIOD ) ){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_a3KeyTyped

    private void a4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a4KeyTyped
        // TODO add your handling code here:
      // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==evt.VK_MINUS || c==evt.VK_PERIOD ) ){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_a4KeyTyped

    private void a5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a5KeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==evt.VK_MINUS || c==evt.VK_PERIOD ) ){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_a5KeyTyped

    private void a6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a6KeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==evt.VK_MINUS || c==evt.VK_PERIOD ) ){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_a6KeyTyped

    private void a7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a7KeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==evt.VK_MINUS || c==evt.VK_PERIOD ) ){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_a7KeyTyped

    private void a8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a8KeyTyped
        // TODO add your handling code here:
       // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==evt.VK_MINUS || c==evt.VK_PERIOD ) ){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_a8KeyTyped

    private void a9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a9KeyTyped
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==evt.VK_MINUS || c==evt.VK_PERIOD ) ){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_a9KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        a1.setText("");
        a2.setText("");
        a3.setText("");
        a4.setText("");
        a5.setText("");
        a6.setText("");
        a7.setText("");
        a8.setText("");
        a9.setText("");
        System.out.println(getBounds());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==evt.VK_MINUS || c==evt.VK_PERIOD ) ){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_b1KeyTyped

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_b2KeyTyped

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_b3KeyTyped

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_b4KeyTyped

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_b5KeyTyped

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b6KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_b6KeyTyped

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_b7KeyTyped

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_b8KeyTyped

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b9KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_b9KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         jButton3.setEnabled(false);
               Andar();

        
 
        
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed
        // TODO add your handling code here:
        
        if(choose.getText().equals("Inverse")){
        choose.setText("Cofactor");
        }else if(choose.getText().equals("Cofactor")){
        choose.setText("Inverse");
        }
        
       answersaMATRIX();
        
        
    }//GEN-LAST:event_chooseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JTextField a9;
    public javax.swing.JTextField b1;
    public javax.swing.JTextField b2;
    public javax.swing.JTextField b3;
    public javax.swing.JTextField b4;
    public javax.swing.JTextField b5;
    public javax.swing.JTextField b6;
    public javax.swing.JTextField b7;
    public javax.swing.JTextField b8;
    public javax.swing.JTextField b9;
    private javax.swing.JButton choose;
    private javax.swing.JLabel jAnswer;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    
}